'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: application_cache
Experimental: True
'''

from dataclasses import dataclass, field
import typing

from .types import *
from ..page import types as page



def enable() -> typing.Generator[dict,dict,None]:
    '''
    Enables application cache domain notifications.
    '''

    cmd_dict = {
        'method': 'ApplicationCache.enable',
    }
    response = yield cmd_dict


def get_application_cache_for_frame(frame_id: page.FrameId) -> typing.Generator[dict,dict,ApplicationCache]:
    '''
    Returns relevant application cache data for the document in given frame.
    
    :param frame_id: Identifier of the frame containing document whose application cache is retrieved.
    :returns: Relevant application cache data for the document in given frame.
    '''

    cmd_dict = {
        'method': 'ApplicationCache.getApplicationCacheForFrame',
        'params': {
            'frameId': frame_id,
        }
    }
    response = yield cmd_dict
    return ApplicationCache.from_response(response['applicationCache'])


def get_frames_with_manifests() -> typing.Generator[dict,dict,typing.List['FrameWithManifest']]:
    '''
    Returns array of frame identifiers with manifest urls for each frame containing a document
    associated with some application cache.
    :returns: Array of frame identifiers with manifest urls for each frame containing a document
    associated with some application cache.
    '''

    cmd_dict = {
        'method': 'ApplicationCache.getFramesWithManifests',
    }
    response = yield cmd_dict
    return [FrameWithManifest.from_response(i) for i in response['frameIds']]


def get_manifest_for_frame(frame_id: page.FrameId) -> typing.Generator[dict,dict,str]:
    '''
    Returns manifest URL for document in the given frame.
    
    :param frame_id: Identifier of the frame containing document whose manifest is retrieved.
    :returns: Manifest URL for document in the given frame.
    '''

    cmd_dict = {
        'method': 'ApplicationCache.getManifestForFrame',
        'params': {
            'frameId': frame_id,
        }
    }
    response = yield cmd_dict
    return str(response['manifestURL'])


