'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: application_cache
Experimental: True
'''

from dataclasses import dataclass, field
import typing

from ..page import types as page



@dataclass
class ApplicationCacheResource:
    '''
    Detailed application cache resource information.
    '''
    #: Resource url.
    url: str

    #: Resource size.
    size: int

    #: Resource type.
    type_: str

    @classmethod
    def from_response(cls, response):
        return cls(
            url=str(response.get('url')),
            size=int(response.get('size')),
            type_=str(response.get('type')),
        )


@dataclass
class ApplicationCache:
    '''
    Detailed application cache information.
    '''
    #: Manifest URL.
    manifest_url: str

    #: Application cache size.
    size: float

    #: Application cache creation time.
    creation_time: float

    #: Application cache update time.
    update_time: float

    #: Application cache resources.
    resources: typing.List['ApplicationCacheResource']

    @classmethod
    def from_response(cls, response):
        return cls(
            manifest_url=str(response.get('manifestURL')),
            size=float(response.get('size')),
            creation_time=float(response.get('creationTime')),
            update_time=float(response.get('updateTime')),
            resources=[ApplicationCacheResource.from_response(i) for i in response.get('resources')],
        )


@dataclass
class FrameWithManifest:
    '''
    Frame identifier - manifest URL pair.
    '''
    #: Frame identifier.
    frame_id: page.FrameId

    #: Manifest URL.
    manifest_url: str

    #: Application cache status.
    status: int

    @classmethod
    def from_response(cls, response):
        return cls(
            frame_id=page.FrameId.from_response(response.get('frameId')),
            manifest_url=str(response.get('manifestURL')),
            status=int(response.get('status')),
        )

