'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: device_orientation
Experimental: True
'''

from dataclasses import dataclass, field
import typing

from .types import *


def clear_device_orientation_override() -> typing.Generator[dict,dict,None]:
    '''
    Clears the overridden Device Orientation.
    '''

    cmd_dict = {
        'method': 'DeviceOrientation.clearDeviceOrientationOverride',
    }
    response = yield cmd_dict


def set_device_orientation_override(alpha: float, beta: float, gamma: float) -> typing.Generator[dict,dict,None]:
    '''
    Overrides the Device Orientation.
    
    :param alpha: Mock alpha
    :param beta: Mock beta
    :param gamma: Mock gamma
    '''

    cmd_dict = {
        'method': 'DeviceOrientation.setDeviceOrientationOverride',
        'params': {
            'alpha': alpha,
            'beta': beta,
            'gamma': gamma,
        }
    }
    response = yield cmd_dict


