'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: cast
Experimental: True
'''

from cdp.util import T_JSON_DICT
from dataclasses import dataclass
import enum
import typing

from .types import *


@dataclass
class SinksUpdated:
    '''
    This is fired whenever the list of available sinks changes. A sink is a
    device or a software surface that you can cast to.
    '''
    #: This is fired whenever the list of available sinks changes. A sink is a
    #: device or a software surface that you can cast to.
    sinks: typing.List['Sink']

    # These fields are used for internal purposes and are not part of CDP
    _domain = 'Cast'
    _method = 'sinksUpdated'

    @classmethod
    def from_json(cls, json: dict) -> 'SinksUpdated':
        return cls(
            sinks=[Sink.from_json(i) for i in json['sinks']],
        )


@dataclass
class IssueUpdated:
    '''
    This is fired whenever the outstanding issue/error message changes.
    |issueMessage| is empty if there is no issue.
    '''
    #: This is fired whenever the outstanding issue/error message changes.
    #: |issueMessage| is empty if there is no issue.
    issue_message: str

    # These fields are used for internal purposes and are not part of CDP
    _domain = 'Cast'
    _method = 'issueUpdated'

    @classmethod
    def from_json(cls, json: dict) -> 'IssueUpdated':
        return cls(
            issue_message=str(json['issueMessage']),
        )

