'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: indexed_db
Experimental: True
'''

from dataclasses import dataclass, field
import typing

from .types import *


def clear_object_store(security_origin: str, database_name: str, object_store_name: str) -> typing.Generator[dict,dict,None]:
    '''
    Clears all entries from an object store.
    
    :param security_origin: Security origin.
    :param database_name: Database name.
    :param object_store_name: Object store name.
    '''

    cmd_dict = {
        'method': 'IndexedDB.clearObjectStore',
        'params': {
            'securityOrigin': security_origin,
            'databaseName': database_name,
            'objectStoreName': object_store_name,
        }
    }
    response = yield cmd_dict


def delete_database(security_origin: str, database_name: str) -> typing.Generator[dict,dict,None]:
    '''
    Deletes a database.
    
    :param security_origin: Security origin.
    :param database_name: Database name.
    '''

    cmd_dict = {
        'method': 'IndexedDB.deleteDatabase',
        'params': {
            'securityOrigin': security_origin,
            'databaseName': database_name,
        }
    }
    response = yield cmd_dict


def delete_object_store_entries(security_origin: str, database_name: str, object_store_name: str, key_range: KeyRange) -> typing.Generator[dict,dict,None]:
    '''
    Delete a range of entries from an object store
    
    :param security_origin: 
    :param database_name: 
    :param object_store_name: 
    :param key_range: Range of entry keys to delete
    '''

    cmd_dict = {
        'method': 'IndexedDB.deleteObjectStoreEntries',
        'params': {
            'securityOrigin': security_origin,
            'databaseName': database_name,
            'objectStoreName': object_store_name,
            'keyRange': key_range,
        }
    }
    response = yield cmd_dict


def disable() -> typing.Generator[dict,dict,None]:
    '''
    Disables events from backend.
    '''

    cmd_dict = {
        'method': 'IndexedDB.disable',
    }
    response = yield cmd_dict


def enable() -> typing.Generator[dict,dict,None]:
    '''
    Enables events from backend.
    '''

    cmd_dict = {
        'method': 'IndexedDB.enable',
    }
    response = yield cmd_dict


def request_data(security_origin: str, database_name: str, object_store_name: str, index_name: str, skip_count: int, page_size: int, key_range: KeyRange) -> typing.Generator[dict,dict,dict]:
    '''
    Requests data from object store or index.
    
    :param security_origin: Security origin.
    :param database_name: Database name.
    :param object_store_name: Object store name.
    :param index_name: Index name, empty string for object store data requests.
    :param skip_count: Number of records to skip.
    :param page_size: Number of records to fetch.
    :param key_range: Key range.
    :returns: a dict with the following keys:
        * objectStoreDataEntries: Array of object store data entries.
        * hasMore: If true, there are more entries to fetch in the given range.
    '''

    cmd_dict = {
        'method': 'IndexedDB.requestData',
        'params': {
            'securityOrigin': security_origin,
            'databaseName': database_name,
            'objectStoreName': object_store_name,
            'indexName': index_name,
            'skipCount': skip_count,
            'pageSize': page_size,
            'keyRange': key_range,
        }
    }
    response = yield cmd_dict
    return {
        'objectStoreDataEntries': [DataEntry.from_response(i) for i in response['objectStoreDataEntries']],
        'hasMore': bool(response['hasMore']),
    }


def get_metadata(security_origin: str, database_name: str, object_store_name: str) -> typing.Generator[dict,dict,dict]:
    '''
    Gets metadata of an object store
    
    :param security_origin: Security origin.
    :param database_name: Database name.
    :param object_store_name: Object store name.
    :returns: a dict with the following keys:
        * entriesCount: the entries count
        * keyGeneratorValue: the current value of key generator, to become the next inserted
    key into the object store. Valid if objectStore.autoIncrement
    is true.
    '''

    cmd_dict = {
        'method': 'IndexedDB.getMetadata',
        'params': {
            'securityOrigin': security_origin,
            'databaseName': database_name,
            'objectStoreName': object_store_name,
        }
    }
    response = yield cmd_dict
    return {
        'entriesCount': float(response['entriesCount']),
        'keyGeneratorValue': float(response['keyGeneratorValue']),
    }


def request_database(security_origin: str, database_name: str) -> typing.Generator[dict,dict,DatabaseWithObjectStores]:
    '''
    Requests database with given name in given frame.
    
    :param security_origin: Security origin.
    :param database_name: Database name.
    :returns: Database with an array of object stores.
    '''

    cmd_dict = {
        'method': 'IndexedDB.requestDatabase',
        'params': {
            'securityOrigin': security_origin,
            'databaseName': database_name,
        }
    }
    response = yield cmd_dict
    return DatabaseWithObjectStores.from_response(response['databaseWithObjectStores'])


def request_database_names(security_origin: str) -> typing.Generator[dict,dict,typing.List]:
    '''
    Requests database names for given security origin.
    
    :param security_origin: Security origin.
    :returns: Database names for origin.
    '''

    cmd_dict = {
        'method': 'IndexedDB.requestDatabaseNames',
        'params': {
            'securityOrigin': security_origin,
        }
    }
    response = yield cmd_dict
    return [str(i) for i in response['databaseNames']]


