'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: css
Experimental: True
'''

from dataclasses import dataclass, field
import typing

from .types import *
from ..dom import types as dom
from ..page import types as page



class CSS:
    @staticmethod
    def add_rule(style_sheet_id: StyleSheetId, rule_text: str, location: SourceRange) -> CSSRule:
        '''
        Inserts a new rule with the given `ruleText` in a stylesheet with given `styleSheetId`, at the
        position specified by `location`.
        
        :param style_sheet_id: The css style sheet identifier where a new rule should be inserted.
        :param rule_text: The text of a new rule.
        :param location: Text position of a new rule in the target style sheet.
        :returns: The newly created rule.
        '''

        cmd_dict = {
            'method': 'CSS.addRule',
            'params': {
                'styleSheetId': style_sheet_id,
                'ruleText': rule_text,
                'location': location,
            }
        }
        response = yield cmd_dict
        return CSSRule.from_response(response['rule'])

    @staticmethod
    def collect_class_names(style_sheet_id: StyleSheetId) -> typing.List:
        '''
        Returns all class names from specified stylesheet.
        
        :param style_sheet_id: 
        :returns: Class name list.
        '''

        cmd_dict = {
            'method': 'CSS.collectClassNames',
            'params': {
                'styleSheetId': style_sheet_id,
            }
        }
        response = yield cmd_dict
        return [str(i) for i in response['classNames']]

    @staticmethod
    def create_style_sheet(frame_id: page.FrameId) -> StyleSheetId:
        '''
        Creates a new special "via-inspector" stylesheet in the frame with given `frameId`.
        
        :param frame_id: Identifier of the frame where "via-inspector" stylesheet should be created.
        :returns: Identifier of the created "via-inspector" stylesheet.
        '''

        cmd_dict = {
            'method': 'CSS.createStyleSheet',
            'params': {
                'frameId': frame_id,
            }
        }
        response = yield cmd_dict
        return StyleSheetId.from_response(response['styleSheetId'])

    @staticmethod
    def disable() -> None:
        '''
        Disables the CSS agent for the given page.
        '''

        cmd_dict = {
            'method': 'CSS.disable',
        }
        response = yield cmd_dict

    @staticmethod
    def enable() -> None:
        '''
        Enables the CSS agent for the given page. Clients should not assume that the CSS agent has been
        enabled until the result of this command is received.
        '''

        cmd_dict = {
            'method': 'CSS.enable',
        }
        response = yield cmd_dict

    @staticmethod
    def force_pseudo_state(node_id: dom.NodeId, forced_pseudo_classes: typing.List) -> None:
        '''
        Ensures that the given node will have specified pseudo-classes whenever its style is computed by
        the browser.
        
        :param node_id: The element id for which to force the pseudo state.
        :param forced_pseudo_classes: Element pseudo classes to force when computing the element's style.
        '''

        cmd_dict = {
            'method': 'CSS.forcePseudoState',
            'params': {
                'nodeId': node_id,
                'forcedPseudoClasses': forced_pseudo_classes,
            }
        }
        response = yield cmd_dict

    @staticmethod
    def get_background_colors(node_id: dom.NodeId) -> dict:
        '''
        
        
        :param node_id: Id of the node to get background colors for.
        :returns: a dict with the following keys:
            * backgroundColors: The range of background colors behind this element, if it contains any visible text. If no
        visible text is present, this will be undefined. In the case of a flat background color,
        this will consist of simply that color. In the case of a gradient, this will consist of each
        of the color stops. For anything more complicated, this will be an empty array. Images will
        be ignored (as if the image had failed to load).
            * computedFontSize: The computed font size for this node, as a CSS computed value string (e.g. '12px').
            * computedFontWeight: The computed font weight for this node, as a CSS computed value string (e.g. 'normal' or
        '100').
        '''

        cmd_dict = {
            'method': 'CSS.getBackgroundColors',
            'params': {
                'nodeId': node_id,
            }
        }
        response = yield cmd_dict
        return {
                'backgroundColors': [str(i) for i in response['backgroundColors']],
                'computedFontSize': str.from_response(response['computedFontSize']),
                'computedFontWeight': str.from_response(response['computedFontWeight']),
            }

    @staticmethod
    def get_computed_style_for_node(node_id: dom.NodeId) -> typing.List['CSSComputedStyleProperty']:
        '''
        Returns the computed style for a DOM node identified by `nodeId`.
        
        :param node_id: 
        :returns: Computed style for the specified DOM node.
        '''

        cmd_dict = {
            'method': 'CSS.getComputedStyleForNode',
            'params': {
                'nodeId': node_id,
            }
        }
        response = yield cmd_dict
        return [CSSComputedStyleProperty.from_response(i) for i in response['computedStyle']]

    @staticmethod
    def get_inline_styles_for_node(node_id: dom.NodeId) -> dict:
        '''
        Returns the styles defined inline (explicitly in the "style" attribute and implicitly, using DOM
        attributes) for a DOM node identified by `nodeId`.
        
        :param node_id: 
        :returns: a dict with the following keys:
            * inlineStyle: Inline style for the specified DOM node.
            * attributesStyle: Attribute-defined element style (e.g. resulting from "width=20 height=100%").
        '''

        cmd_dict = {
            'method': 'CSS.getInlineStylesForNode',
            'params': {
                'nodeId': node_id,
            }
        }
        response = yield cmd_dict
        return {
                'inlineStyle': CSSStyle.from_response(response['inlineStyle']),
                'attributesStyle': CSSStyle.from_response(response['attributesStyle']),
            }

    @staticmethod
    def get_matched_styles_for_node(node_id: dom.NodeId) -> dict:
        '''
        Returns requested styles for a DOM node identified by `nodeId`.
        
        :param node_id: 
        :returns: a dict with the following keys:
            * inlineStyle: Inline style for the specified DOM node.
            * attributesStyle: Attribute-defined element style (e.g. resulting from "width=20 height=100%").
            * matchedCSSRules: CSS rules matching this node, from all applicable stylesheets.
            * pseudoElements: Pseudo style matches for this node.
            * inherited: A chain of inherited styles (from the immediate node parent up to the DOM tree root).
            * cssKeyframesRules: A list of CSS keyframed animations matching this node.
        '''

        cmd_dict = {
            'method': 'CSS.getMatchedStylesForNode',
            'params': {
                'nodeId': node_id,
            }
        }
        response = yield cmd_dict
        return {
                'inlineStyle': CSSStyle.from_response(response['inlineStyle']),
                'attributesStyle': CSSStyle.from_response(response['attributesStyle']),
                'matchedCSSRules': [RuleMatch.from_response(i) for i in response['matchedCSSRules']],
                'pseudoElements': [PseudoElementMatches.from_response(i) for i in response['pseudoElements']],
                'inherited': [InheritedStyleEntry.from_response(i) for i in response['inherited']],
                'cssKeyframesRules': [CSSKeyframesRule.from_response(i) for i in response['cssKeyframesRules']],
            }

    @staticmethod
    def get_media_queries() -> typing.List['CSSMedia']:
        '''
        Returns all media queries parsed by the rendering engine.
        :returns: 
        '''

        cmd_dict = {
            'method': 'CSS.getMediaQueries',
        }
        response = yield cmd_dict
        return [CSSMedia.from_response(i) for i in response['medias']]

    @staticmethod
    def get_platform_fonts_for_node(node_id: dom.NodeId) -> typing.List['PlatformFontUsage']:
        '''
        Requests information about platform fonts which we used to render child TextNodes in the given
        node.
        
        :param node_id: 
        :returns: Usage statistics for every employed platform font.
        '''

        cmd_dict = {
            'method': 'CSS.getPlatformFontsForNode',
            'params': {
                'nodeId': node_id,
            }
        }
        response = yield cmd_dict
        return [PlatformFontUsage.from_response(i) for i in response['fonts']]

    @staticmethod
    def get_style_sheet_text(style_sheet_id: StyleSheetId) -> str:
        '''
        Returns the current textual content for a stylesheet.
        
        :param style_sheet_id: 
        :returns: The stylesheet text.
        '''

        cmd_dict = {
            'method': 'CSS.getStyleSheetText',
            'params': {
                'styleSheetId': style_sheet_id,
            }
        }
        response = yield cmd_dict
        return str.from_response(response['text'])

    @staticmethod
    def set_effective_property_value_for_node(node_id: dom.NodeId, property_name: str, value: str) -> None:
        '''
        Find a rule with the given active property for the given node and set the new value for this
        property
        
        :param node_id: The element id for which to set property.
        :param property_name: 
        :param value: 
        '''

        cmd_dict = {
            'method': 'CSS.setEffectivePropertyValueForNode',
            'params': {
                'nodeId': node_id,
                'propertyName': property_name,
                'value': value,
            }
        }
        response = yield cmd_dict

    @staticmethod
    def set_keyframe_key(style_sheet_id: StyleSheetId, range: SourceRange, key_text: str) -> Value:
        '''
        Modifies the keyframe rule key text.
        
        :param style_sheet_id: 
        :param range: 
        :param key_text: 
        :returns: The resulting key text after modification.
        '''

        cmd_dict = {
            'method': 'CSS.setKeyframeKey',
            'params': {
                'styleSheetId': style_sheet_id,
                'range': range,
                'keyText': key_text,
            }
        }
        response = yield cmd_dict
        return Value.from_response(response['keyText'])

    @staticmethod
    def set_media_text(style_sheet_id: StyleSheetId, range: SourceRange, text: str) -> CSSMedia:
        '''
        Modifies the rule selector.
        
        :param style_sheet_id: 
        :param range: 
        :param text: 
        :returns: The resulting CSS media rule after modification.
        '''

        cmd_dict = {
            'method': 'CSS.setMediaText',
            'params': {
                'styleSheetId': style_sheet_id,
                'range': range,
                'text': text,
            }
        }
        response = yield cmd_dict
        return CSSMedia.from_response(response['media'])

    @staticmethod
    def set_rule_selector(style_sheet_id: StyleSheetId, range: SourceRange, selector: str) -> SelectorList:
        '''
        Modifies the rule selector.
        
        :param style_sheet_id: 
        :param range: 
        :param selector: 
        :returns: The resulting selector list after modification.
        '''

        cmd_dict = {
            'method': 'CSS.setRuleSelector',
            'params': {
                'styleSheetId': style_sheet_id,
                'range': range,
                'selector': selector,
            }
        }
        response = yield cmd_dict
        return SelectorList.from_response(response['selectorList'])

    @staticmethod
    def set_style_sheet_text(style_sheet_id: StyleSheetId, text: str) -> str:
        '''
        Sets the new stylesheet text.
        
        :param style_sheet_id: 
        :param text: 
        :returns: URL of source map associated with script (if any).
        '''

        cmd_dict = {
            'method': 'CSS.setStyleSheetText',
            'params': {
                'styleSheetId': style_sheet_id,
                'text': text,
            }
        }
        response = yield cmd_dict
        return str.from_response(response['sourceMapURL'])

    @staticmethod
    def set_style_texts(edits: typing.List['StyleDeclarationEdit']) -> typing.List['CSSStyle']:
        '''
        Applies specified style edits one after another in the given order.
        
        :param edits: 
        :returns: The resulting styles after modification.
        '''

        cmd_dict = {
            'method': 'CSS.setStyleTexts',
            'params': {
                'edits': edits,
            }
        }
        response = yield cmd_dict
        return [CSSStyle.from_response(i) for i in response['styles']]

    @staticmethod
    def start_rule_usage_tracking() -> None:
        '''
        Enables the selector recording.
        '''

        cmd_dict = {
            'method': 'CSS.startRuleUsageTracking',
        }
        response = yield cmd_dict

    @staticmethod
    def stop_rule_usage_tracking() -> typing.List['RuleUsage']:
        '''
        Stop tracking rule usage and return the list of rules that were used since last call to
        `takeCoverageDelta` (or since start of coverage instrumentation)
        :returns: 
        '''

        cmd_dict = {
            'method': 'CSS.stopRuleUsageTracking',
        }
        response = yield cmd_dict
        return [RuleUsage.from_response(i) for i in response['ruleUsage']]

    @staticmethod
    def take_coverage_delta() -> typing.List['RuleUsage']:
        '''
        Obtain list of rules that became used since last call to this method (or since start of coverage
        instrumentation)
        :returns: 
        '''

        cmd_dict = {
            'method': 'CSS.takeCoverageDelta',
        }
        response = yield cmd_dict
        return [RuleUsage.from_response(i) for i in response['coverage']]

