'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: css
Experimental: True
'''

from dataclasses import dataclass, field
import typing

from .types import *


@dataclass
class FontsUpdated:
    '''
    Fires whenever a web font is updated.  A non-empty font parameter indicates a successfully loaded
    web font
    '''
    #: Fires whenever a web font is updated.  A non-empty font parameter indicates a successfully loaded
    #: web font
    font: FontFace


@dataclass
class MediaQueryResultChanged:
    '''
    Fires whenever a MediaQuery result changes (for example, after a browser window has been
    resized.) The current implementation considers only viewport-dependent media features.
    '''
    pass


@dataclass
class StyleSheetAdded:
    '''
    Fired whenever an active document stylesheet is added.
    '''
    #: Fired whenever an active document stylesheet is added.
    header: CSSStyleSheetHeader


@dataclass
class StyleSheetChanged:
    '''
    Fired whenever a stylesheet is changed as a result of the client operation.
    '''
    #: Fired whenever a stylesheet is changed as a result of the client operation.
    style_sheet_id: StyleSheetId


@dataclass
class StyleSheetRemoved:
    '''
    Fired whenever an active document stylesheet is removed.
    '''
    #: Fired whenever an active document stylesheet is removed.
    style_sheet_id: StyleSheetId

