'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: page
Experimental: False
'''

from dataclasses import dataclass, field
import typing

from .types import *
from ..network import types as network
from ..runtime import types as runtime



@dataclass
class DomContentEventFired:
    timestamp: network.MonotonicTime


@dataclass
class FrameAttached:
    '''
    Fired when frame has been attached to its parent.
    '''
    #: Fired when frame has been attached to its parent.
    frame_id: FrameId

    #: Fired when frame has been attached to its parent.
    parent_frame_id: FrameId

    #: Fired when frame has been attached to its parent.
    stack: runtime.StackTrace


@dataclass
class FrameClearedScheduledNavigation:
    '''
    Fired when frame no longer has a scheduled navigation.
    '''
    #: Fired when frame no longer has a scheduled navigation.
    frame_id: FrameId


@dataclass
class FrameDetached:
    '''
    Fired when frame has been detached from its parent.
    '''
    #: Fired when frame has been detached from its parent.
    frame_id: FrameId


@dataclass
class FrameNavigated:
    '''
    Fired once navigation of the frame has completed. Frame is now associated with the new loader.
    '''
    #: Fired once navigation of the frame has completed. Frame is now associated with the new loader.
    frame: Frame


@dataclass
class FrameResized:
    pass


@dataclass
class FrameRequestedNavigation:
    '''
    Fired when a renderer-initiated navigation is requested.
    Navigation may still be cancelled after the event is issued.
    '''
    #: Fired when a renderer-initiated navigation is requested.
    #: Navigation may still be cancelled after the event is issued.
    frame_id: FrameId

    #: Fired when a renderer-initiated navigation is requested.
    #: Navigation may still be cancelled after the event is issued.
    reason: ClientNavigationReason

    #: Fired when a renderer-initiated navigation is requested.
    #: Navigation may still be cancelled after the event is issued.
    url: str


@dataclass
class FrameScheduledNavigation:
    '''
    Fired when frame schedules a potential navigation.
    '''
    #: Fired when frame schedules a potential navigation.
    frame_id: FrameId

    #: Fired when frame schedules a potential navigation.
    delay: float

    #: Fired when frame schedules a potential navigation.
    reason: str

    #: Fired when frame schedules a potential navigation.
    url: str


@dataclass
class FrameStartedLoading:
    '''
    Fired when frame has started loading.
    '''
    #: Fired when frame has started loading.
    frame_id: FrameId


@dataclass
class FrameStoppedLoading:
    '''
    Fired when frame has stopped loading.
    '''
    #: Fired when frame has stopped loading.
    frame_id: FrameId


@dataclass
class DownloadWillBegin:
    '''
    Fired when page is about to start a download.
    '''
    #: Fired when page is about to start a download.
    frame_id: FrameId

    #: Fired when page is about to start a download.
    url: str


@dataclass
class InterstitialHidden:
    '''
    Fired when interstitial page was hidden
    '''
    pass


@dataclass
class InterstitialShown:
    '''
    Fired when interstitial page was shown
    '''
    pass


@dataclass
class JavascriptDialogClosed:
    '''
    Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) has been
    closed.
    '''
    #: Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) has been
    #: closed.
    result: bool

    #: Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) has been
    #: closed.
    user_input: str


@dataclass
class JavascriptDialogOpening:
    '''
    Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) is about to
    open.
    '''
    #: Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) is about to
    #: open.
    url: str

    #: Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) is about to
    #: open.
    message: str

    #: Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) is about to
    #: open.
    type: DialogType

    #: Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) is about to
    #: open.
    has_browser_handler: bool

    #: Fired when a JavaScript initiated dialog (alert, confirm, prompt, or onbeforeunload) is about to
    #: open.
    default_prompt: str


@dataclass
class LifecycleEvent:
    '''
    Fired for top level page lifecycle events such as navigation, load, paint, etc.
    '''
    #: Fired for top level page lifecycle events such as navigation, load, paint, etc.
    frame_id: FrameId

    #: Fired for top level page lifecycle events such as navigation, load, paint, etc.
    loader_id: network.LoaderId

    #: Fired for top level page lifecycle events such as navigation, load, paint, etc.
    name: str

    #: Fired for top level page lifecycle events such as navigation, load, paint, etc.
    timestamp: network.MonotonicTime


@dataclass
class LoadEventFired:
    timestamp: network.MonotonicTime


@dataclass
class NavigatedWithinDocument:
    '''
    Fired when same-document navigation happens, e.g. due to history API usage or anchor navigation.
    '''
    #: Fired when same-document navigation happens, e.g. due to history API usage or anchor navigation.
    frame_id: FrameId

    #: Fired when same-document navigation happens, e.g. due to history API usage or anchor navigation.
    url: str


@dataclass
class ScreencastFrame:
    '''
    Compressed image data requested by the `startScreencast`.
    '''
    #: Compressed image data requested by the `startScreencast`.
    data: str

    #: Compressed image data requested by the `startScreencast`.
    metadata: ScreencastFrameMetadata

    #: Compressed image data requested by the `startScreencast`.
    session_id: int


@dataclass
class ScreencastVisibilityChanged:
    '''
    Fired when the page with currently enabled screencast was shown or hidden `.
    '''
    #: Fired when the page with currently enabled screencast was shown or hidden `.
    visible: bool


@dataclass
class WindowOpen:
    '''
    Fired when a new window is going to be opened, via window.open(), link click, form submission,
    etc.
    '''
    #: Fired when a new window is going to be opened, via window.open(), link click, form submission,
    #: etc.
    url: str

    #: Fired when a new window is going to be opened, via window.open(), link click, form submission,
    #: etc.
    window_name: str

    #: Fired when a new window is going to be opened, via window.open(), link click, form submission,
    #: etc.
    window_features: typing.List

    #: Fired when a new window is going to be opened, via window.open(), link click, form submission,
    #: etc.
    user_gesture: bool


@dataclass
class CompilationCacheProduced:
    '''
    Issued for every compilation cache generated. Is only available
    if Page.setGenerateCompilationCache is enabled.
    '''
    #: Issued for every compilation cache generated. Is only available
    #: if Page.setGenerateCompilationCache is enabled.
    url: str

    #: Issued for every compilation cache generated. Is only available
    #: if Page.setGenerateCompilationCache is enabled.
    data: str

