'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: io
Experimental: False
'''

from cdp.util import T_JSON_DICT
from dataclasses import dataclass
import enum
import typing


class StreamHandle(str):
    '''
    This is either obtained from another method or specifed as `blob:&lt;uuid&gt;` where
    `&lt;uuid&gt` is an UUID of a Blob.
    '''
    def to_json(self) -> str:
        return self

    @classmethod
    def from_json(cls, json: str) -> 'StreamHandle':
        return cls(json)

    def __repr__(self):
        return 'StreamHandle({})'.format(str.__repr__(self))


