'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: inspector
Experimental: True
'''

from dataclasses import dataclass, field
import typing

from .types import *


@dataclass
class Detached:
    '''
    Fired when remote debugging connection is about to be terminated. Contains detach reason.
    '''
    #: Fired when remote debugging connection is about to be terminated. Contains detach reason.
    reason: str


@dataclass
class TargetCrashed:
    '''
    Fired when debugging target has crashed
    '''
    pass


@dataclass
class TargetReloadedAfterCrash:
    '''
    Fired when debugging target has reloaded after crash
    '''
    pass

