'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: schema
Experimental: False
'''

from cdp.util import T_JSON_DICT
from dataclasses import dataclass
import enum
import typing

from .types import *


def get_domains() -> typing.Generator[T_JSON_DICT,T_JSON_DICT,typing.List['Domain']]:
    '''
    Returns supported domains.
    :returns: List of supported domains.
    '''
    cmd_dict: T_JSON_DICT = {
        'method': 'Schema.getDomains',
    }
    json = yield cmd_dict
    return [Domain.from_json(i) for i in json['domains']]


