'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: web_audio
Experimental: True
'''

from dataclasses import dataclass, field
import typing

from .types import *


@dataclass
class ContextCreated:
    '''
    Notifies that a new BaseAudioContext has been created.
    '''
    #: Notifies that a new BaseAudioContext has been created.
    context: BaseAudioContext


@dataclass
class ContextDestroyed:
    '''
    Notifies that existing BaseAudioContext has been destroyed.
    '''
    #: Notifies that existing BaseAudioContext has been destroyed.
    context_id: ContextId


@dataclass
class ContextChanged:
    '''
    Notifies that existing BaseAudioContext has changed some properties (id stays the same)..
    '''
    #: Notifies that existing BaseAudioContext has changed some properties (id stays the same)..
    context: BaseAudioContext

