'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: fetch
Experimental: True
'''

from cdp.util import T_JSON_DICT
from dataclasses import dataclass
import enum
import typing

from .types import *
from ..network import types as network
from ..page import types as page



@dataclass
class RequestPaused:
    '''
    Issued when the domain is enabled and the request URL matches the
    specified filter. The request is paused until the client responds
    with one of continueRequest, failRequest or fulfillRequest.
    The stage of the request can be determined by presence of responseErrorReason
    and responseStatusCode -- the request is at the response stage if either
    of these fields is present and in the request stage otherwise.
    '''
    #: Issued when the domain is enabled and the request URL matches the
    #: specified filter. The request is paused until the client responds
    #: with one of continueRequest, failRequest or fulfillRequest.
    #: The stage of the request can be determined by presence of responseErrorReason
    #: and responseStatusCode -- the request is at the response stage if either
    #: of these fields is present and in the request stage otherwise.
    request_id: RequestId

    #: Issued when the domain is enabled and the request URL matches the
    #: specified filter. The request is paused until the client responds
    #: with one of continueRequest, failRequest or fulfillRequest.
    #: The stage of the request can be determined by presence of responseErrorReason
    #: and responseStatusCode -- the request is at the response stage if either
    #: of these fields is present and in the request stage otherwise.
    request: network.Request

    #: Issued when the domain is enabled and the request URL matches the
    #: specified filter. The request is paused until the client responds
    #: with one of continueRequest, failRequest or fulfillRequest.
    #: The stage of the request can be determined by presence of responseErrorReason
    #: and responseStatusCode -- the request is at the response stage if either
    #: of these fields is present and in the request stage otherwise.
    frame_id: page.FrameId

    #: Issued when the domain is enabled and the request URL matches the
    #: specified filter. The request is paused until the client responds
    #: with one of continueRequest, failRequest or fulfillRequest.
    #: The stage of the request can be determined by presence of responseErrorReason
    #: and responseStatusCode -- the request is at the response stage if either
    #: of these fields is present and in the request stage otherwise.
    resource_type: network.ResourceType

    #: Issued when the domain is enabled and the request URL matches the
    #: specified filter. The request is paused until the client responds
    #: with one of continueRequest, failRequest or fulfillRequest.
    #: The stage of the request can be determined by presence of responseErrorReason
    #: and responseStatusCode -- the request is at the response stage if either
    #: of these fields is present and in the request stage otherwise.
    response_error_reason: typing.Optional[network.ErrorReason] = None

    #: Issued when the domain is enabled and the request URL matches the
    #: specified filter. The request is paused until the client responds
    #: with one of continueRequest, failRequest or fulfillRequest.
    #: The stage of the request can be determined by presence of responseErrorReason
    #: and responseStatusCode -- the request is at the response stage if either
    #: of these fields is present and in the request stage otherwise.
    response_status_code: typing.Optional[int] = None

    #: Issued when the domain is enabled and the request URL matches the
    #: specified filter. The request is paused until the client responds
    #: with one of continueRequest, failRequest or fulfillRequest.
    #: The stage of the request can be determined by presence of responseErrorReason
    #: and responseStatusCode -- the request is at the response stage if either
    #: of these fields is present and in the request stage otherwise.
    response_headers: typing.Optional[typing.List['HeaderEntry']] = None

    #: Issued when the domain is enabled and the request URL matches the
    #: specified filter. The request is paused until the client responds
    #: with one of continueRequest, failRequest or fulfillRequest.
    #: The stage of the request can be determined by presence of responseErrorReason
    #: and responseStatusCode -- the request is at the response stage if either
    #: of these fields is present and in the request stage otherwise.
    network_id: typing.Optional[RequestId] = None

    # These fields are used for internal purposes and are not part of CDP
    _domain = 'Fetch'
    _method = 'requestPaused'

    @classmethod
    def from_json(cls, json: dict) -> 'RequestPaused':
        response_error_reason = network.ErrorReason.from_json(json['responseErrorReason']) if 'responseErrorReason' in json else None
        response_status_code = int(json['responseStatusCode']) if 'responseStatusCode' in json else None
        response_headers = [HeaderEntry.from_json(i) for i in json['responseHeaders']] if 'responseHeaders' in json else None
        network_id = RequestId.from_json(json['networkId']) if 'networkId' in json else None
        return cls(
            request_id=RequestId.from_json(json['requestId']),
            request=network.Request.from_json(json['request']),
            frame_id=page.FrameId.from_json(json['frameId']),
            resource_type=network.ResourceType.from_json(json['resourceType']),
            response_error_reason=response_error_reason,
            response_status_code=response_status_code,
            response_headers=response_headers,
            network_id=network_id,
        )


@dataclass
class AuthRequired:
    '''
    Issued when the domain is enabled with handleAuthRequests set to true.
    The request is paused until client responds with continueWithAuth.
    '''
    #: Issued when the domain is enabled with handleAuthRequests set to true.
    #: The request is paused until client responds with continueWithAuth.
    request_id: RequestId

    #: Issued when the domain is enabled with handleAuthRequests set to true.
    #: The request is paused until client responds with continueWithAuth.
    request: network.Request

    #: Issued when the domain is enabled with handleAuthRequests set to true.
    #: The request is paused until client responds with continueWithAuth.
    frame_id: page.FrameId

    #: Issued when the domain is enabled with handleAuthRequests set to true.
    #: The request is paused until client responds with continueWithAuth.
    resource_type: network.ResourceType

    #: Issued when the domain is enabled with handleAuthRequests set to true.
    #: The request is paused until client responds with continueWithAuth.
    auth_challenge: AuthChallenge

    # These fields are used for internal purposes and are not part of CDP
    _domain = 'Fetch'
    _method = 'authRequired'

    @classmethod
    def from_json(cls, json: dict) -> 'AuthRequired':
        return cls(
            request_id=RequestId.from_json(json['requestId']),
            request=network.Request.from_json(json['request']),
            frame_id=page.FrameId.from_json(json['frameId']),
            resource_type=network.ResourceType.from_json(json['resourceType']),
            auth_challenge=AuthChallenge.from_json(json['authChallenge']),
        )

