'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: dom_debugger
Experimental: False
'''

from dataclasses import dataclass, field
import typing

from ..dom import types as dom
from ..runtime import types as runtime



class DOMBreakpointType:
    '''
    DOM breakpoint type.
    '''
    SUBTREE_MODIFIED = "subtree-modified"
    ATTRIBUTE_MODIFIED = "attribute-modified"
    NODE_REMOVED = "node-removed"


@dataclass
class EventListener:
    '''
    Object event listener.
    '''
    #: `EventListener`'s type.
    type_: str

    #: `EventListener`'s useCapture.
    use_capture: bool

    #: `EventListener`'s passive flag.
    passive: bool

    #: `EventListener`'s once flag.
    once: bool

    #: Script id of the handler code.
    script_id: runtime.ScriptId

    #: Line number in the script (0-based).
    line_number: int

    #: Column number in the script (0-based).
    column_number: int

    #: Event handler function value.
    handler: runtime.RemoteObject

    #: Event original handler function value.
    original_handler: runtime.RemoteObject

    #: Node the listener is added to (if any).
    backend_node_id: dom.BackendNodeId

    @classmethod
    def from_response(cls, response):
        return cls(
            type_=str(response.get('type')),
            use_capture=bool(response.get('useCapture')),
            passive=bool(response.get('passive')),
            once=bool(response.get('once')),
            script_id=runtime.ScriptId.from_response(response.get('scriptId')),
            line_number=int(response.get('lineNumber')),
            column_number=int(response.get('columnNumber')),
            handler=runtime.RemoteObject.from_response(response.get('handler')),
            original_handler=runtime.RemoteObject.from_response(response.get('originalHandler')),
            backend_node_id=dom.BackendNodeId.from_response(response.get('backendNodeId')),
        )

