'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: layer_tree
Experimental: True
'''

from dataclasses import dataclass, field
import typing

from .types import *
from ..dom import types as dom



@dataclass
class LayerPainted:
    layer_id: LayerId

    clip: dom.Rect


@dataclass
class LayerTreeDidChange:
    layers: typing.List['Layer']

