'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: tethering
Experimental: True
'''

from dataclasses import dataclass, field
import typing

from .types import *


def bind(port: int) -> typing.Generator[dict,dict,None]:
    '''
    Request browser port binding.
    
    :param port: Port number to bind.
    '''

    cmd_dict = {
        'method': 'Tethering.bind',
        'params': {
            'port': port,
        }
    }
    response = yield cmd_dict


def unbind(port: int) -> typing.Generator[dict,dict,None]:
    '''
    Request browser port unbinding.
    
    :param port: Port number to unbind.
    '''

    cmd_dict = {
        'method': 'Tethering.unbind',
        'params': {
            'port': port,
        }
    }
    response = yield cmd_dict


