'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: tethering
Experimental: True
'''

from dataclasses import dataclass, field
import typing

from .types import *


class Tethering:
    @staticmethod
    def bind(port: int) -> None:
        '''
        Request browser port binding.
        
        :param port: Port number to bind.
        '''

        cmd_dict = {
            'method': 'Tethering.bind',
            'params': {
                'port': port,
            }
        }
        response = yield cmd_dict

    @staticmethod
    def unbind(port: int) -> None:
        '''
        Request browser port unbinding.
        
        :param port: Port number to unbind.
        '''

        cmd_dict = {
            'method': 'Tethering.unbind',
            'params': {
                'port': port,
            }
        }
        response = yield cmd_dict

