'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: performance
Experimental: False
'''

from cdp.util import T_JSON_DICT
from dataclasses import dataclass
import enum
import typing

from .types import *


@dataclass
class Metrics:
    '''
    Current values of the metrics.
    '''
    #: Current values of the metrics.
    metrics: typing.List['Metric']

    #: Current values of the metrics.
    title: str

    # These fields are used for internal purposes and are not part of CDP
    _domain = 'Performance'
    _method = 'metrics'

    @classmethod
    def from_json(cls, json: dict) -> 'Metrics':
        return cls(
            metrics=[Metric.from_json(i) for i in json['metrics']],
            title=str(json['title']),
        )

