'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: headless_experimental
Experimental: True
'''

from cdp.util import T_JSON_DICT
from dataclasses import dataclass
import enum
import typing

from .types import *


@dataclass
class NeedsBeginFramesChanged:
    '''
    Issued when the target starts or stops needing BeginFrames.
    '''
    #: Issued when the target starts or stops needing BeginFrames.
    needs_begin_frames: bool

    # These fields are used for internal purposes and are not part of CDP
    _domain = 'HeadlessExperimental'
    _method = 'needsBeginFramesChanged'

    @classmethod
    def from_json(cls, json: dict) -> 'NeedsBeginFramesChanged':
        return cls(
            needs_begin_frames=bool(json['needsBeginFrames']),
        )

