'''
DO NOT EDIT THIS FILE

This file is generated from the CDP definitions. If you need to make changes,
edit the generator and regenerate all of the modules.

Domain: web_authn
Experimental: True
'''

from dataclasses import dataclass, field
import typing


